@startuml

left to right direction

package "Infrastructure" {
  class RecipeFileRepository {
    - recipesFolder: File
    + RecipeFileRepository(recipesFolder: File)
    + saveRecipe(recipe: Recipe)
    + deleteRecipe(recipe: Recipe): boolean
    + getRecipes(): List<Recipe>
    + getRecipe(id: String): Recipe
  }

  package "Application" {
    class DialogService {
      - recipeRepository: RecipeRepository
      + DialogService(recipeRepository: RecipeRepository)
    }

    package "Domain" {
      interface RecipeRepository {
        + saveRecipe(recipe: Recipe)
        + deleteRecipe(recipe: Recipe): boolean
        + getRecipes(): List<Recipe>
        + getRecipe(id: String): Recipe
      }
    }
  }
}

DialogService -> RecipeRepository
RecipeRepository <|.. RecipeFileRepository

@enduml