@startuml

left to right direction

class AutoChef {
  + main(args: String[])
}

class DialogService {
  - recipeRepository: RecipeRepository
  + DialogService(recipeRepository: RecipeRepository)
}

interface RecipeRepository {
  + saveRecipe(recipe: Recipe)
  + deleteRecipe(recipe: Recipe): boolean
  + getRecipes(): List<Recipe>
  + getRecipe(id: String): Recipe
}

class RecipeFileRepository {
  - recipesFolder: File
  + RecipeFileRepository(recipesFolder: File)
  + saveRecipe(recipe: Recipe)
  + deleteRecipe(recipe: Recipe): boolean
  + getRecipes(): List<Recipe>
  + getRecipe(id: String): Recipe
}

AutoChef -> RecipeFileRepository
AutoChef -> DialogService
DialogService -> RecipeRepository
RecipeRepository <|.. RecipeFileRepository

@enduml