# Entities
MealPlanEntity: Meal Plan Entity {
  listofmeals: *MealEntity\[\]
  startdate: Start date
  enddate: End date
  grocerylist: *GroceryListEntity
}  

MealPlanEntity.listofmeals -> MealEntity: 1:n
MealPlanEntity.grocerylist -> GroceryListEntity: 1:1

MealEntity: Meal Entity {
  name: Name
  recipesteps: *RecipeStepEntity\[\]
  ingredients: *GroceryListEntryEntity\[\]
}  
MealEntity.recipesteps -> RecipeStepEntity: 1:n
MealEntity.ingredients -> GroceryListEntryEntity: 1:n

GroceryListEntity: Grocery List Entity {
  grocerylist: *GroceryListEntryEntity\[\]
  mealplan: *MealPlanEntity
}  
GroceryListEntity.grocerylist -> GroceryListEntryEntity: 1:n

RecipeStepEntity: Recipe Step Entity {
  step: Step Number
  ingredients: *GroceryListEntryEntity\[\]
  description: Description
}  

GroceryListEntryEntity: Grocery List Entry Entity { # rename
  ingredient: *VO.Ingredient
  unit: *VO.Unit
  quantity: *VO.Quantity
}
GroceryListEntryEntity.ingredient -> ValueObjects.ingredient
GroceryListEntryEntity.unit -> ValueObjects.unit
GroceryListEntryEntity.quantity -> ValueObjects.quantity

# Value Objects
ValueObjects: Value Objects {
  ingredient: Ingredient
  unit: Unit
  quantity: Quantity
}

# Services 
GenerateListService: Generate List Service {
  shape: hexagon
  fill: "#ffdef1"
}
GenerateListService <-> MealPlanEntity
GenerateListService <-> GroceryListEntity

FilterService: Filter Service {
  shape: hexagon
  fill: "#ffdef1"
}
FilterService <-> MealEntity
FilterService <-> GroceryListEntity

OutputService: Output Service {
  shape: hexagon
  fill: "#ffdef1"
}
OutputService <-> MealEntity
OutputService <-> GroceryListEntity
OutputService <-> RecipeStepEntity

InputService: Input Service {
  shape: hexagon
  fill: "#ffdef1"
}
InputService <-> MealEntity
InputService <-> GroceryListEntity
