# Services
GenerateListService: Generate List Service {
  shape: hexagon
  fill: "#ffdef1"
}
GenerateListService -> MealPlanEntity
GenerateListService -> GroceryListEntity
GenerateListService -> FilterService
GenerateListService -> OutputService
GenerateListService -> InputService

FilterService: Filter Service {
  shape: hexagon
  fill: "#ffdef1"
}

OutputService: Output Service {
  shape: hexagon
  fill: "#ffdef1"
}
OutputService -> MealPlanEntity
OutputService -> GroceryListEntity
OutputService -> RecipeEntity

InputService: Input Service {
  shape: hexagon
  fill: "#ffdef1"
}
InputService -> MealEntity
InputService -> GroceryListEntity

# Entities
MealPlanEntity: Meal Plan Entity {
  listofmeals: *Meal\[\]
  startdate: Start date
  enddate: End date
  grocerylist: *GroceryListEntity
}
MealPlanEntity.listofmeals -> MealEntity: 1:n
MealPlanEntity.grocerylist -> GroceryListEntity: 1:1

MealEntity: Meal Entity {
  recipe: *RecipeEntity
  people: Adjusted number\nof people
  near: MealPlanEntity
}  
MealEntity.recipe -> RecipeEntity: 1:1

RecipeEntity: Recipe Entity {
  name: Name
  recipesteps: *RecipeStepEntity\[\]
  grocerylist: *GroceryListEntity
}  
RecipeEntity.recipesteps -> RecipeStepEntity: 1:n
RecipeEntity.grocerylist -> GroceryListEntity: 1:1

RecipeStepEntity: Recipe Step Entity {
  step: Step Number
  ingredients: *GroceryListEntryEntity\[\]
  description: Description
  near: RecipeEntity
}

GroceryListEntity: Grocery List Entity {
  list: *GroceryListEntryEntity\[\]
  mealplan: *MealPlanEntity
}  
GroceryListEntity.list -> GroceryListEntryEntity: 1:n

GroceryListEntryEntity: Grocery List Entry Entity { # rename
  ingredient: *VO.Ingredient
  unit: *VO.Unit
  quantity: *VO.Quantity
  near: GroceryListEntity
}
GroceryListEntryEntity.ingredient -> ValueObjects.ingredient
GroceryListEntryEntity.unit -> ValueObjects.unit
GroceryListEntryEntity.quantity -> ValueObjects.quantity

# Value Objects
ValueObjects: Value Objects {
  ingredient: Ingredient
  unit: Unit
  quantity: Quantity
}

x: |latex
\\cdot
| {near: bottom-right}
